### PR TITLE
fix podspec to support react native autolink

### PR DESCRIPTION
**Pull request by akread**
autolink did not work with the previous podspec setup

https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

Screen Shot 2019-12-04 at 1 14 40 PM
Screen Shot 2019-12-04 at 1 15 07 PM

### CODE REVIEW

**Comment by akread** [comment]
Thoughts on getting this merged? 🤔

**Comment by akread** [comment]
@FlorianBergmann @15matias15 any thoughts on getting this merged? I am running on the commit from my fork until this is merged. I'd like get back on the main repo.

**Comment by FlorianBergmann** [comment]
@akread Thanks for the pull request and sorry for the late reply. I will merge it and then publish a new version when I am back in the office.

Should be either on the 2nd or 3rd of January.

**Comment by FlorianBergmann** [comment]
@akread it should be published now. Sorry that it took so long, it slipped my mind.

**Comment by akread** [comment]
No problem. Thank you for publishing.

**Pull request merged**
